"""added handle-title

Revision ID: 2a6a5559eeb9
Revises: 8f006c755a54
Create Date: 2024-05-06 20:41:37.186166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2a6a5559eeb9'
down_revision: Union[str, None] = '8f006c755a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('handle_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_problem_handle_title'), 'problem', ['handle_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_handle_title'), table_name='problem')
    op.drop_column('problem', 'handle_title')
    # ### end Alembic commands ###
