"""testing databases

Revision ID: 3a58fe51090f
Revises: 
Create Date: 2024-04-28 16:45:49.422066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3a58fe51090f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_difficulty'), 'problem', ['difficulty'], unique=False)
    op.create_index(op.f('ix_problem_title'), 'problem', ['title'], unique=False)
    op.create_table('testcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_case', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('problems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('output_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='problems_pkey')
    )
    op.drop_table('testcase')
    op.drop_index(op.f('ix_problem_title'), table_name='problem')
    op.drop_index(op.f('ix_problem_difficulty'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
