"""input/output number of variables added

Revision ID: 6ef957d4f406
Revises: 2a6a5559eeb9
Create Date: 2024-05-07 02:38:54.767226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ef957d4f406'
down_revision: Union[str, None] = '2a6a5559eeb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('input_number_variables', sa.Integer(), nullable=False))
    op.add_column('testcase', sa.Column('output_number_variables', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testcase', 'output_number_variables')
    op.drop_column('testcase', 'input_number_variables')
    # ### end Alembic commands ###
