"""modifying database, example deleted from problem db

Revision ID: 7c2fa4b593c1
Revises: cd1e3c2e6b12
Create Date: 2024-04-30 19:22:54.336396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7c2fa4b593c1'
down_revision: Union[str, None] = 'cd1e3c2e6b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'example')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
