"""testing databases

Revision ID: 7eed894d0416
Revises: 3a58fe51090f
Create Date: 2024-04-28 16:58:36.491619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7eed894d0416'
down_revision: Union[str, None] = '3a58fe51090f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'testcase', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'user_id')
    # ### end Alembic commands ###
