"""create relationship between category and problems

Revision ID: 8f006c755a54
Revises: bd9c46009e22
Create Date: 2024-05-01 02:08:09.056996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8f006c755a54'
down_revision: Union[str, None] = 'bd9c46009e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemcategorylink',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'category_id')
    )
    op.drop_constraint('problem_category_id_fkey', 'problem', type_='foreignkey')
    op.drop_column('problem', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('problem_category_id_fkey', 'problem', 'category', ['category_id'], ['id'])
    op.drop_table('problemcategorylink')
    # ### end Alembic commands ###
