"""input/output number of variables added to problems

Revision ID: abaab239aa0c
Revises: 6ef957d4f406
Create Date: 2024-05-07 02:43:06.445806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'abaab239aa0c'
down_revision: Union[str, None] = '6ef957d4f406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('input_number_variables', sa.Integer(), nullable=False))
    op.add_column('problem', sa.Column('output_number_variables', sa.Integer(), nullable=False))
    op.drop_column('testcase', 'output_number_variables')
    op.drop_column('testcase', 'input_number_variables')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('input_number_variables', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('testcase', sa.Column('output_number_variables', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('problem', 'output_number_variables')
    op.drop_column('problem', 'input_number_variables')
    # ### end Alembic commands ###
