"""testing databases

Revision ID: ace9b2c99fde
Revises: 7eed894d0416
Create Date: 2024-04-28 19:25:35.098835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ace9b2c99fde'
down_revision: Union[str, None] = '7eed894d0416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problem_user_id_fkey', 'problem', type_='foreignkey')
    op.drop_column('problem', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('problem_user_id_fkey', 'problem', 'testcase', ['user_id'], ['id'])
    # ### end Alembic commands ###
