"""modifying and add more databases

Revision ID: d1be30a6f573
Revises: 97c39cf27e3c
Create Date: 2024-04-30 23:11:05.612673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd1be30a6f573'
down_revision: Union[str, None] = '97c39cf27e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('result', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('submission', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'created_at')
    op.drop_column('result', 'created_at')
    op.drop_column('problem', 'created_at')
    # ### end Alembic commands ###
